### ISSUE TITLE
Trouble installing on apple silicon M1

### ISSUE THREAD

**Issue by khlevon** [aimhubio/aimrocks#11]
Problem
-
When trying to install `aim` (which depends on `aimrocks`) with pip  on MacOS with M1 chip I am getting this error:
`
ERROR: Could not find a version that satisfies the requirement aimrocks==0.0.10 (from aim) (from versions: none)
ERROR: No matching distribution found for aimrocks==0.0.10
`

I suspect this happens because there are no pre-built binaries for M1 chip. To fix this issue please publish pre-built binaries for M1 arm architecture.
To save you time and resources I'm providing pre-built binaries on the specified environment from `master` branch using command `python setup.py sdist bdist_wheel  `, if you need something from my side to fix this issue please feel free to contact me.

[Download M1 binaries](https://github.com/aimhubio/aimrocks/files/7914128/aimrocks_0.10.0_macos_arm64.tar.gz)

Environment info:
-
OS: macOS 12.1 21C52 arm64 
Host: MacBookPro18,3 
Kernel: 21.2.0 
DE: Aqua  
CPU: Apple M1 Pro 
GPU: Apple M1 Pro
Python: 3.10.x or 3.9.x
Pip: 21.2.4

Reproducing code example:
-
`pip install aim==3.3.5`
or
`pip install aimrocks==0.0.10`

**Comment by alberttorosyan** [comment]
Hi @khlevon! Thanks for reporting the issue. Will make sure to include M1 binary distribution for `aimrocks`.

**Comment by jonasdebeukelaer** [comment]
Possibly doing something stupid _but_, when trying to install from your tar @khlevon I get the following error:

```
$ pip install aimrocks_0.10.0_macos_arm64.tar.gz
Processing ./aimrocks_0.10.0_macos_arm64.tar.gz
ERROR: file:///Users/path/to/dir/aimrocks_0.10.0_macos_arm64.tar.gz does not appear to be a Python project: neither 'setup.py' nor 'pyproject.toml' found.
```
Am I doing something wrong? I tried to build from source myself but a) not sure which commit is `v0.1.0` (no tags) and b) need to install rocksdb so figured I'd ask first.

Thanks!

**Comment by mahnerak** [comment]
We're preparing to ship M1 builds of `aimrocks` and `aim`.
In fact, as of April 20 we have version `0.2.1` that comes with arm64 builds.

@jonasdebeukelaer 
Just try to `pip install aimrocks==0.2.1` (it should work even without specifying the version explicitly)

**Comment by jonasdebeukelaer** [comment]
@mahnerak thanks, unfortunately I need version 0.1.0 for installing `aim`. Apologies I should have included that in the above.

i.e.
```
$ pip install aim==3.8.1                        
Collecting aim==3.8.1
  Using cached aim-3.8.1.tar.gz (15.0 MB)
  Preparing metadata (setup.py) ... done
Collecting aimrecords==0.0.7
  Using cached aimrecords-0.0.7-py2.py3-none-any.whl (28 kB)
ERROR: Could not find a version that satisfies the requirement aimrocks==0.1.0 (from aim) (from versions: 0.1.3a14, 0.2.0.dev1, 0.2.0.dev2, 0.2.0.dev3, 0.2.0, 0.2.1)
ERROR: No matching distribution found for aimrocks==0.1.0
```

**Comment by mahnerak** [comment]
@jonasdebeukelaer Sure, than I'll suggest to use pre-release dev versions of aim that support m1 out of the box.
You just need `pip install aim==3.9.0.dev23`.
Let me know if anything goes wrong!
(And please let me know if everything worked well)

> EDIT 2: but it seems it's for macosx 12.0, I'm on 12.2 currently alas

macos12.2 supports builds for macos12.0

**Comment by jonasdebeukelaer** [comment]
Ah amazing thanks, pre-release seems to be working 👌 
RE: build issue, turns out I was using the wrong python version (3.8 instead of 3.9) 🤦

**Comment by raphaelauv** [comment]
@khlevon can you close this issue ? thanks
