### ISSUE TITLE
[QUESTION] disable WAL

### ISSUE THREAD

**Issue by raphaelauv** [aimhubio/aimrocks#17]
Thanks for your lib !!

Is it possible to disable the WAL at write ? thanks

**Comment by mahnerak** [comment]
Sure! Just pass `disable_wal=True`.
Here's the definition:
https://github.com/aimhubio/aimrocks/blob/db068474a693a90f209a81d97337864b5a6e1513/src/aimrocks/lib_rocksdb.pyx#L1751-L1755

**Comment by raphaelauv** [comment]
thanks

and for WriteBatch

```python

batch = aimrocks.WriteBatch()
for key, val in values:
    batch.put(key, val)
rocks_db.write(batch, disable_wal=True)
```
