### ISSUE TITLE
Feature: add support for OpenAsSecondary

### ISSUE THREAD

**Issue by ofek** [aimhubio/aimrocks#2]
Doc: https://github.com/facebook/rocksdb/wiki/Secondary-instance  
Code: https://github.com/facebook/rocksdb/blob/v6.22.1/include/rocksdb/db.h#L192-L215

**Comment by mahnerak** [comment]
We have in our plans to add this in `aimrocks` to make read-only instances (from Aim UI) to observe the data logged with `aim` in real time.

Can you elaborate on what's your case for Secondary instances?

**Comment by mahnerak** [comment]
@ofek, feature added! Thanks for sharing your use-case with us.

**Comment by ofek** [comment]
thank you very much! is there documentation/an example?
