### ISSUE TITLE
Python 3.12 wheels

### ISSUE THREAD

**Issue by judahrand** [aimhubio/aimrocks#32]
Python 3.12 has been out for quite sometime now. Could you please provide wheels so that `aim` is easily installable on Python 3.12?

**Comment by koustuvsinha** [comment]
Hi, any ETA on this?

**Comment by Tinnyflame** [comment]
Is there any update?

**Comment by judahrand** [comment]
I suspect it won't get merged soon but I've put up a PR to build Python 3.12 wheels for this package.
